# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "user" ]
    paths: [ "solution.py"]
  pull_request:
    branches: [ "user" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: show working dir
        run: echo ${GITHUB_WORKSPACE}
      
      # Feeds data to solution.py using the runners shell
      - name: Feed data to solution.py
        run: |
          (cat input/input1.txt | python3 solution.py) > output.txt
          (cat output.txt | python3 scripts/compare.py)
